services:
  - type: worker
    runtime: rust
    name: sp1-blobstream-operator
    repo: https://github.com/succinctlabs/sp1-blobstream
    region: frankfurt
    plan: pro
    rootDir: script
    buildCommand: rm -rf build.rs && cargo build --bin operator --release
    startCommand: cargo run --bin operator --release
    autoDeploy: true
    envVars:
      - key: TENDERMINT_RPC_URL
        value: https://rpc.lunaroasis.net/
      - key: SP1_PROVER
        value: network
      - key: CHAIN_ID
        value: 11155111
      - key: CONTRACT_ADDRESS
        value: 0xf043007d74B0BA6F61fB80b6c8bE07e3BBD81fcC
      - key: PRIVATE_KEY
        sync: false
      - key: RPC_URL
        sync: false
      - key: SP1_PRIVATE_KEY
        sync: false
