[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.24'
optimizer = true
optimizer_runs = 200
# @see {@link https://github.com/foundry-rs/foundry/issues/4060}
auto_detect_remappings = false
evm_version = "cancun"


[profile.default.optimizer_details]
# constantOptimizer = true
yul = true

[fmt]
line_length = 100
tab_width = 4
func_attrs_with_params_multiline = true
ignore = ["lib/**"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
