[profile.default]
src = "src"
out = "out"
solc = '0.8.26'
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./out" },
    { access = "read-write", path = "./deployments" },
]

[profile.deploy]
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
tab_width = 4
func_attrs_with_params_multiline = true
ignore = ["lib/**"]

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
holesky = "${RPC_HOLESKY}"
arbitrum = "${RPC_ARBITRUM}"
arbitrum_sepolia = "${RPC_ARBITRUM_SEPOLIA}"
base = "${RPC_BASE}"
base_sepolia = "${RPC_BASE_SEPOLIA}"
scroll = "${RPC_SCROLL}"
scroll_sepolia = "${RPC_SCROLL_SEPOLIA}"

[etherscan]
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}", url = "${MAINNET_ETHERSCAN_API_URL}" }
sepolia = { key = "${SEPOLIA_ETHERSCAN_API_KEY}", url = "${SEPOLIA_ETHERSCAN_API_URL}" }
holesky = { key = "${HOLESKY_ETHERSCAN_API_KEY}", url = "${HOLESKY_ETHERSCAN_API_URL}" }
arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}", url = "${ARBITRUM_ETHERSCAN_API_URL}" }
arbitrum_sepolia = { key = "${ARBITRUM_SEPOLIA_ETHERSCAN_API_KEY}", url = "${ARBITRUM_SEPOLIA_ETHERSCAN_API_URL}" }
base = { key = "${BASE_ETHERSCAN_API_KEY}", url = "${BASE_ETHERSCAN_API_URL}" }
base_sepolia = { key = "${BASE_SEPOLIA_ETHERSCAN_API_KEY}", url = "${BASE_SEPOLIA_ETHERSCAN_API_URL}", chain = 84532 }
scroll = { key = "${SCROLL_ETHERSCAN_API_KEY}", url = "${SCROLL_ETHERSCAN_API_URL}" }
scroll_sepolia = { key = "${SCROLL_SEPOLIA_ETHERSCAN_API_KEY}", url = "${SCROLL_SEPOLIA_ETHERSCAN_API_URL}" }
